### ISSUE TITLE
Autocompletion in ZSH

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#168] opened 2022-01-22 11:13 UTC
> BTW, in zsh, completions doesn't work for flags. In bash, works fine. Since it is primarily targeted to bash, I am not sure if it is a bug or if an issue is needed.

_Originally posted by @insign in https://github.com/DannyBen/bashly/issues/165#issuecomment-1018999898_

**Comment by DannyBen** [comment] 2022-01-22 11:21
@insign - autocompletion should wok in zsh in a similar way. Zsh needs to be configured to know how to handle bash-style completions.

If you are using Oh-My-Zsh, I believe it should work out of the box.
If not, you need to ensure that your `~/.zshrc` contains these lines:

```
# Load bash completion functions
autoload -Uz +X compinit && compinit
autoload -Uz +X bashcompinit && bashcompinit
```

Finally - I suggest the following test case, to try and find out if the problem is something in your bashly configuration, or in the code that generates the completions.

1. Go to a new empty directory
2. Run `bashly init` to create a minimal bashly config
3. Run `bashly add comp script` to create a minimal completions file named `completions.bash`
4. Run `source ./completions.bash`

Now, you should be able to see completions for `cli download` and `cli upload`.
Try `cli download --<TAB>` to see if it completes.

For me, when running this in a containerized ZSH shell, this works.

**Comment by ndepal** [comment] 2022-01-27 15:49
I have also noticed this problem in the past. I'm using Oh-My-Zsh, and as you say I also think bash completions should work in general.

Following your instructions above, I get partially working suggestions:
```
cli <TAB>
download   -h         --help     upload     -v         --version
```

But subcommands don't work right:
```
cli download <TAB>
download   -h         --help     upload     -v         --version
```
I get the same suggestions as just for `cli`.

When I was investigating this a few months ago, I believe I tracked it down to the following line in the completions function:
```
local comp_line="${COMP_WORDS[*]:1}"
```
This does not result in the correct value being assigned to `com_line` because array indexing works differently in ZSH.

**Comment by DannyBen** [comment] 2022-01-27 16:40
I have now also tried it with a non-docerized zsh, with and without Oh My Zsh - both work as expected.

If anyone using zsh can test with the above provided `completions.bash`, it would help - the only reason I can think of that this does not reproduce for me, and fails for others is that you might be using an older version of bashly or completely.

**Comment by ndepal** [comment] 2022-01-28 10:24
I tried following your instructions. I can reproduce the issue that way as well: https://asciinema.org/a/6ksQG74HFh71HYznsdEBrA7OW

I believe your recording actually also has the issue.
the completions for `cli download --<TAB>` look (mostly) right by coincidence. But they're the suggestions that apply for `cli <TAB>`. You're also getting the suggestion `--version`. Isn't that wrong `cli download --version`?

You can make it more obvious by adding flags to the `cli download` command that don't exist elsewhere. And as shown in my recording, `cli download <TAB>` (without already adding `--`) will suggest `download` and `upload` again.

This is consistent with what I saw before. And I believe it's because in ZSH `local comp_line="${COMP_WORDS[*]:1}"` is always empty, so the switch always goes to `''*)`.

**Comment by DannyBen** [comment] 2022-01-28 11:09
Ok, nice - thanks for recording.
Do you happen to know what is the alternative to `local comp_line="${COMP_WORDS[*]:1}"` that works in both ZSH and abash?

**Comment by DannyBen** [comment] 2022-01-28 11:23
Heh... I don't know who wrote this StackOverflow question - but its the same problem, and uses my `completely` gem :)
https://stackoverflow.com/questions/69675174/bash-completion-does-not-work-in-zsh-oh-my-zsh-because-comp-words-is-not-an-arra

**Comment by DannyBen** [comment] 2022-01-28 11:48
I think I found a solution that seems to work in both bash and zsh as expected:

source this file:

```bash
#!/usr/bin/env bash

_cli_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  # local comp_line="${COMP_WORDS[*]:1}"          # OLD
  local comp_line="${COMP_WORDS[@]:1}"            # NEW
  echo "COMP_WORDS: ${COMP_WORDS[*]}" >> out.txt  # DEBUG
  echo "comp_line:  ${comp_line[*]}" >> out.txt   # DEBUG

  case "$comp_line" in
    'download'*) COMPREPLY=($(compgen -W "--force --help -f -h" -- "$cur")) ;;
    'upload'*) COMPREPLY=($(compgen -W "--help --password --user -h -p -u" -- "$cur")) ;;
    ''*) COMPREPLY=($(compgen -W "--help --version -h -v download upload" -- "$cur")) ;;
  esac
}

complete -F _cli_completions cli
```

**Comment by ndepal** [comment] 2022-01-28 13:00
Yes that's me :smile:

Your suggested change works for me as well.

**Comment by DannyBen** [comment] 2022-01-28 13:02
Cool! I will merge the change into completely, release a version, and then release a bashly version that forces the fixed dependency in its gemspec, followed aby a docker release.

Thanks for the help!

**Closed** 2022-01-28 13:16 UTC
Labels: bug, help wanted

**Comment by DannyBen** [comment] 2022-01-28 13:24
Version 0.7.2 is released on RubyGems and Docker Hub with the fix.

**Comment by DannyBen** [comment] 2022-01-28 16:03
No. This is the intended behavior.

You can see the intended output clearly by running `bashly add comp yaml`. This generates the input file to the completely gem:

```yaml
---
cli:
- "--help"
- "--version"
- "-h"
- "-v"
- download
cli download:
- "--arch"
- "--help"
- "-h"
- amd64
- arm64
```

The completely gem creates a simplified completions script. It only sets completion arrays for commands and subcommands, and these arrays are offered regardless of their allowed position.

The reason it is done like this, is simple: In order to also support positional logic, you end up with a completions script that it sometimes thousands of lines long. See the completions script for [git](https://github.com/git/git/blob/master/contrib/completion/git-completion.bash) or [docker](https://github.com/docker/cli/blob/master/contrib/completion/bash/docker).

For me, writing this kind of scripts for completion is unacceptable, and this is the reason I created completely: To allow a simple way to create usable completions. The price is that they are not perfect.

**Comment by ndepal** [comment] 2022-01-28 16:29
Alright, fair enough. Thanks for the explanation and the tip.
